package org.packman.server.logic

class DifferentMapPlayer {
    private val playerMaps = listOf(
        PlayerMap(
            map = listOf(
                intArrayOf(WALL, WALL, WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL),
                intArrayOf(WALL, EMPT, WALL,EMPT,EMPT,EMPT,EMPT,WALL,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,WALL,EMPT,EMPT,EMPT,WALL),
                intArrayOf(WALL, EMPT, WALL,EMPT,WALL,EMPT,EMPT,WALL,WALL,WALL,EMPT,WALL,EMPT,WALL,EMPT,WALL,EMPT,EMPT,EMPT,WALL),
                intArrayOf(WALL, EMPT, WALL,EMPT,WALL,EMPT,EMPT,WALL,EMPT,EMPT,EMPT,WALL,EMPT,WALL,WALL,WALL,WALL,EMPT,EMPT,WALL),
                intArrayOf(WALL, EMPT, WALL,EMPT,WALL,WALL,EMPT,WALL,EMPT,WALL,WALL,WALL,EMPT,EMPT,EMPT,EMPT,WALL,EMPT,EMPT,WALL),
                intArrayOf(WALL, EMPT, EMPT,EMPT,EMPT,WALL,EMPT,WALL,EMPT,EMPT,EMPT,WALL,WALL,WALL,WALL,EMPT,WALL,EMPT,EMPT,WALL),
                intArrayOf(WALL, WALL, WALL,WALL,WALL,WALL,EMPT,WALL,EMPT,WALL,EMPT,WALL,EMPT,EMPT,EMPT,EMPT,WALL,EMPT,EMPT,WALL),
                intArrayOf(WALL, EMPT, EMPT,EMPT,WALL,EMPT,EMPT,WALL,EMPT,WALL,PLAY,WALL,EMPT,WALL,WALL,WALL,WALL,EMPT,EMPT,WALL),
                intArrayOf(WALL, EMPT, WALL,EMPT,WALL,EMPT,WALL,WALL,EMPT,WALL,EMPT,WALL,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,WALL),
                intArrayOf(WALL, EMPT, WALL,EMPT,WALL,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,WALL,WALL,WALL,WALL,WALL,EMPT,WALL),
                intArrayOf(WALL, EMPT, WALL,WALL,WALL,EMPT,WALL,WALL,WALL,WALL,WALL,EMPT,WALL,WALL,EMPT,WALL,EMPT,EMPT,EMPT,WALL),
                intArrayOf(WALL, EMPT, EMPT,EMPT,EMPT,EMPT,WALL,EMPT,EMPT,EMPT,WALL,EMPT,WALL,EMPT,EMPT,WALL,EMPT,WALL,WALL,WALL),
                intArrayOf(WALL, WALL, WALL,EMPT,WALL,EMPT,WALL,EMPT,WALL,WALL,WALL,EMPT,WALL,EMPT,WALL,WALL,EMPT,WALL,EMPT,WALL),
                intArrayOf(WALL, EMPT, EMPT,EMPT,WALL,EMPT,WALL,EMPT,EMPT,EMPT,EMPT,EMPT,WALL,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,WALL),
                intArrayOf(WALL, WALL, WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL),
            ),
            coordinatePlayer = Coordinate(i = 7, j = 10),
            lifeCoins = mutableListOf(),
        ),
        PlayerMap(
            map = listOf(
                intArrayOf(WALL, WALL, WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL),
                intArrayOf(WALL, EMPT, EMPT,EMPT,WALL,EMPT,EMPT,EMPT,EMPT,WALL,EMPT,EMPT,WALL,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,WALL),
                intArrayOf(WALL, WALL, WALL,EMPT,WALL,EMPT,WALL,WALL,EMPT,WALL,EMPT,EMPT,WALL,EMPT,WALL,EMPT,WALL,WALL,EMPT,WALL),
                intArrayOf(WALL, EMPT, EMPT,EMPT,WALL,EMPT,EMPT,EMPT,EMPT,WALL,EMPT,WALL,WALL,EMPT,WALL,EMPT,EMPT,WALL,EMPT,WALL),
                intArrayOf(WALL, EMPT, WALL,EMPT,WALL,WALL,WALL,WALL,EMPT,WALL,EMPT,WALL,PLAY,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,WALL),
                intArrayOf(WALL, EMPT, WALL,EMPT,WALL,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,WALL,EMPT,WALL,EMPT,WALL,EMPT,WALL,EMPT,WALL),
                intArrayOf(WALL, EMPT, WALL,EMPT,WALL,WALL,WALL,EMPT,WALL,EMPT,EMPT,EMPT,EMPT,WALL,EMPT,WALL,EMPT,WALL,EMPT,WALL),
                intArrayOf(WALL, EMPT, EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,WALL,EMPT,WALL,WALL,EMPT,WALL,EMPT,WALL,EMPT,WALL,EMPT,WALL),
                intArrayOf(WALL, WALL, WALL,EMPT,WALL,WALL,EMPT,EMPT,WALL,EMPT,WALL,EMPT,EMPT,WALL,EMPT,WALL,EMPT,WALL,EMPT,WALL),
                intArrayOf(WALL, EMPT, EMPT,EMPT,WALL,EMPT,EMPT,EMPT,WALL,EMPT,WALL,EMPT,EMPT,WALL,EMPT,EMPT,EMPT,WALL,EMPT,WALL),
                intArrayOf(WALL, EMPT, WALL,WALL,WALL,EMPT,WALL,WALL,WALL,EMPT,WALL,WALL,EMPT,WALL,WALL,EMPT,EMPT,WALL,EMPT,WALL),
                intArrayOf(WALL, EMPT, WALL,EMPT,WALL,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,WALL,EMPT,EMPT,WALL,WALL,WALL,WALL,EMPT,WALL),
                intArrayOf(WALL, EMPT, WALL,EMPT,WALL,EMPT,WALL,WALL,WALL,WALL,EMPT,WALL,WALL,EMPT,EMPT,EMPT,WALL,EMPT,EMPT,WALL),
                intArrayOf(WALL, EMPT, EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,WALL,EMPT,EMPT,WALL,EMPT,EMPT,EMPT,WALL,WALL),
                intArrayOf(WALL, WALL, WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL),
            ),
            coordinatePlayer = Coordinate(i = 4, j = 12),
            lifeCoins = mutableListOf(),
        ),
        PlayerMap(
            map = listOf(
                intArrayOf(WALL, WALL, WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL),
                intArrayOf(WALL, EMPT, EMPT,EMPT,EMPT,WALL,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,WALL,EMPT,WALL,EMPT,EMPT,WALL,WALL),
                intArrayOf(WALL, WALL, WALL,WALL,EMPT,WALL,EMPT,WALL,EMPT,WALL,WALL,WALL,EMPT,WALL,EMPT,EMPT,EMPT,WALL,WALL,WALL),
                intArrayOf(WALL, EMPT, EMPT,EMPT,EMPT,WALL,EMPT,WALL,EMPT,WALL,EMPT,EMPT,EMPT,WALL,EMPT,EMPT,WALL,WALL,EMPT,WALL),
                intArrayOf(WALL, EMPT, WALL,WALL,EMPT,WALL,EMPT,WALL,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,WALL,WALL,EMPT,EMPT,WALL),
                intArrayOf(WALL, EMPT, WALL,EMPT,EMPT,EMPT,EMPT,WALL,WALL,WALL,WALL,WALL,EMPT,EMPT,WALL,WALL,EMPT,EMPT,EMPT,WALL),
                intArrayOf(WALL, EMPT, WALL,EMPT,WALL,WALL,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,WALL,WALL,EMPT,EMPT,EMPT,EMPT,WALL),
                intArrayOf(WALL, EMPT, EMPT,EMPT,EMPT,EMPT,EMPT,WALL,WALL,PLAY,WALL,WALL,WALL,WALL,WALL,EMPT,WALL,WALL,EMPT,WALL),
                intArrayOf(WALL, WALL, WALL,WALL,EMPT,EMPT,WALL,WALL,EMPT,EMPT,WALL,EMPT,EMPT,EMPT,WALL,EMPT,WALL,EMPT,EMPT,WALL),
                intArrayOf(WALL, EMPT, EMPT,EMPT,EMPT,WALL,WALL,EMPT,EMPT,EMPT,WALL,WALL,WALL,EMPT,WALL,EMPT,WALL,EMPT,EMPT,WALL),
                intArrayOf(WALL, EMPT, WALL,EMPT,WALL,WALL,EMPT,EMPT,WALL,EMPT,EMPT,EMPT,EMPT,EMPT,WALL,EMPT,WALL,WALL,EMPT,WALL),
                intArrayOf(WALL, EMPT, WALL,WALL,WALL,EMPT,EMPT,WALL,WALL,WALL,EMPT,WALL,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,WALL),
                intArrayOf(WALL, EMPT, WALL,WALL,EMPT,EMPT,WALL,WALL,EMPT,WALL,EMPT,WALL,WALL,WALL,EMPT,WALL,WALL,WALL,EMPT,WALL),
                intArrayOf(WALL, WALL, WALL,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,WALL,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,WALL),
                intArrayOf(WALL, WALL, WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL),
            ),
            coordinatePlayer = Coordinate(i = 7, j = 9),
            lifeCoins = mutableListOf(),
        ),
    )

    fun generateMap() = playerMaps.shuffled().first()
}

private val EMPT = MapLogic.Companion.ParseMap.EMPTY.value
private val WALL = MapLogic.Companion.ParseMap.WALL.value
private val PLAY = MapLogic.Companion.ParseMap.PLAYER.value